//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (4)
//--------------------------------------------------------------------------------
pub extern "api-ms-win-core-psm-appnotify-l1-1-1" fn RegisterAppConstrainedChangeNotification(
    Routine: ?PAPPCONSTRAIN_CHANGE_ROUTINE,
    Context: ?*anyopaque,
    Registration: ?*?*_APPCONSTRAIN_REGISTRATION,
) callconv(.winapi) u32;

pub extern "api-ms-win-core-psm-appnotify-l1-1-0" fn RegisterAppStateChangeNotification(
    Routine: ?PAPPSTATE_CHANGE_ROUTINE,
    Context: ?*anyopaque,
    Registration: ?*?*_APPSTATE_REGISTRATION,
) callconv(.winapi) u32;

pub extern "api-ms-win-core-psm-appnotify-l1-1-1" fn UnregisterAppConstrainedChangeNotification(
    Registration: ?*_APPCONSTRAIN_REGISTRATION,
) callconv(.winapi) void;

pub extern "api-ms-win-core-psm-appnotify-l1-1-0" fn UnregisterAppStateChangeNotification(
    Registration: ?*_APPSTATE_REGISTRATION,
) callconv(.winapi) void;


//--------------------------------------------------------------------------------
// Section: Imports (4)
//--------------------------------------------------------------------------------
const _APPCONSTRAIN_REGISTRATION = @import("../../win32/ui/shell.zig")._APPCONSTRAIN_REGISTRATION;
const _APPSTATE_REGISTRATION = @import("../../win32/ui/shell.zig")._APPSTATE_REGISTRATION;
const PAPPCONSTRAIN_CHANGE_ROUTINE = @import("../../win32/ui/shell.zig").PAPPCONSTRAIN_CHANGE_ROUTINE;
const PAPPSTATE_CHANGE_ROUTINE = @import("../../win32/ui/shell.zig").PAPPSTATE_CHANGE_ROUTINE;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
