//! NOTE: this file is autogenerated, DO NOT MODIFY
pub const audio = @import("media/audio.zig");
pub const device_manager = @import("media/device_manager.zig");
pub const library_sharing_services = @import("media/library_sharing_services.zig");
pub const media_foundation = @import("media/media_foundation.zig");
pub const media_player = @import("media/media_player.zig");
pub const multimedia = @import("media/multimedia.zig");
pub const picture_acquisition = @import("media/picture_acquisition.zig");
pub const speech = @import("media/speech.zig");
pub const streaming = @import("media/streaming.zig");
pub const windows_media_format = @import("media/windows_media_format.zig");
test {
    @import("std").testing.refAllDecls(@This());
}
