//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (1)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows10.0.14393'
pub extern "api-ms-win-core-memory-l1-1-4" fn QueryVirtualMemoryInformation(
    Process: ?HANDLE,
    VirtualAddress: ?*const anyopaque,
    MemoryInformationClass: WIN32_MEMORY_INFORMATION_CLASS,
    /// parameter "MemoryInformationSize" is the size in bytes
    MemoryInformation: ?*anyopaque,
    MemoryInformationSize: usize,
    ReturnSize: ?*usize,
) callconv(.winapi) BOOL;


//--------------------------------------------------------------------------------
// Section: Imports (3)
//--------------------------------------------------------------------------------
const BOOL = i32;
const HANDLE = @import("../win32/foundation.zig").HANDLE;
const WIN32_MEMORY_INFORMATION_CLASS = @import("../win32/system/memory.zig").WIN32_MEMORY_INFORMATION_CLASS;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
