//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (6)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows8.1'
pub extern "api-ms-win-shcore-scaling-l1-1-1" fn GetDpiForMonitor(
    hmonitor: ?HMONITOR,
    dpiType: MONITOR_DPI_TYPE,
    dpiX: ?*u32,
    dpiY: ?*u32,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows8.1'
pub extern "api-ms-win-shcore-scaling-l1-1-1" fn GetProcessDpiAwareness(
    hprocess: ?HANDLE,
    value: ?*PROCESS_DPI_AWARENESS,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows8.1'
pub extern "api-ms-win-shcore-scaling-l1-1-1" fn GetScaleFactorForMonitor(
    hMon: ?HMONITOR,
    pScale: ?*DEVICE_SCALE_FACTOR,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows8.1'
pub extern "api-ms-win-shcore-scaling-l1-1-1" fn RegisterScaleChangeEvent(
    hEvent: ?HANDLE,
    pdwCookie: ?*usize,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows8.1'
pub extern "api-ms-win-shcore-scaling-l1-1-1" fn SetProcessDpiAwareness(
    value: PROCESS_DPI_AWARENESS,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows8.1'
pub extern "api-ms-win-shcore-scaling-l1-1-1" fn UnregisterScaleChangeEvent(
    dwCookie: usize,
) callconv(.winapi) HRESULT;


//--------------------------------------------------------------------------------
// Section: Imports (6)
//--------------------------------------------------------------------------------
const DEVICE_SCALE_FACTOR = @import("../win32/ui/shell/common.zig").DEVICE_SCALE_FACTOR;
const HANDLE = @import("../win32/foundation.zig").HANDLE;
const HMONITOR = @import("../win32/graphics/gdi.zig").HMONITOR;
const HRESULT = @import("../win32/zig.zig").HRESULT;
const MONITOR_DPI_TYPE = @import("../win32/ui/hi_dpi.zig").MONITOR_DPI_TYPE;
const PROCESS_DPI_AWARENESS = @import("../win32/ui/hi_dpi.zig").PROCESS_DPI_AWARENESS;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
