//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (1)
//--------------------------------------------------------------------------------
pub extern "api-ms-win-core-state-helpers-l1-1-0" fn GetRegistryValueWithFallbackW(
    hkeyPrimary: ?HKEY,
    pwszPrimarySubKey: ?[*:0]const u16,
    hkeyFallback: ?HKEY,
    pwszFallbackSubKey: ?[*:0]const u16,
    pwszValue: ?[*:0]const u16,
    dwFlags: u32,
    pdwType: ?*u32,
    /// parameter "cbDataIn" is the size in bytes
    pvData: ?*anyopaque,
    cbDataIn: u32,
    pcbDataOut: ?*u32,
) callconv(.winapi) WIN32_ERROR;


//--------------------------------------------------------------------------------
// Section: Imports (2)
//--------------------------------------------------------------------------------
const HKEY = @import("../win32/system/registry.zig").HKEY;
const WIN32_ERROR = @import("../win32/foundation.zig").WIN32_ERROR;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
