//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (59)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn AddLogContainer(
    hLog: ?HANDLE,
    pcbContainer: ?*u64,
    pwszContainerPath: ?[*:0]u16,
    pReserved: ?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn AddLogContainerSet(
    hLog: ?HANDLE,
    cContainer: u16,
    pcbContainer: ?*u64,
    rgwszContainerPath: [*]?[*:0]u16,
    pReserved: ?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn AdvanceLogBase(
    pvMarshal: ?*anyopaque,
    plsnBase: ?*CLS_LSN,
    fFlags: u32,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn AlignReservedLog(
    pvMarshal: ?*anyopaque,
    cReservedRecords: u32,
    rgcbReservation: ?*i64,
    pcbAlignReservation: ?*i64,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn AllocReservedLog(
    pvMarshal: ?*anyopaque,
    cReservedRecords: u32,
    pcbAdjustment: ?*i64,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn CloseAndResetLogFile(
    hLog: ?HANDLE,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn CreateLogContainerScanContext(
    hLog: ?HANDLE,
    cFromContainer: u32,
    cContainers: u32,
    eScanMode: u8,
    pcxScan: ?*CLS_SCAN_CONTEXT,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn CreateLogFile(
    pszLogFileName: ?[*:0]const u16,
    fDesiredAccess: FILE_ACCESS_FLAGS,
    dwShareMode: FILE_SHARE_MODE,
    psaLogFile: ?*SECURITY_ATTRIBUTES,
    fCreateDisposition: FILE_CREATION_DISPOSITION,
    fFlagsAndAttributes: FILE_FLAGS_AND_ATTRIBUTES,
) callconv(.winapi) ?HANDLE;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn CreateLogMarshallingArea(
    hLog: ?HANDLE,
    pfnAllocBuffer: ?CLFS_BLOCK_ALLOCATION,
    pfnFreeBuffer: ?CLFS_BLOCK_DEALLOCATION,
    pvBlockAllocContext: ?*anyopaque,
    cbMarshallingBuffer: u32,
    cMaxWriteBuffers: u32,
    cMaxReadBuffers: u32,
    ppvMarshal: ?*?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn DeleteLogByHandle(
    hLog: ?HANDLE,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn DeleteLogFile(
    pszLogFileName: ?[*:0]const u16,
    pvReserved: ?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn DeleteLogMarshallingArea(
    pvMarshal: ?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn DeregisterManageableLogClient(
    hLog: ?HANDLE,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn FlushLogBuffers(
    pvMarshal: ?*anyopaque,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn FlushLogToLsn(
    pvMarshalContext: ?*anyopaque,
    plsnFlush: ?*CLS_LSN,
    plsnLastFlushed: ?*CLS_LSN,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn FreeReservedLog(
    pvMarshal: ?*anyopaque,
    cReservedRecords: u32,
    pcbAdjustment: ?*i64,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn GetLogContainerName(
    hLog: ?HANDLE,
    cidLogicalContainer: u32,
    pwstrContainerName: ?[*:0]const u16,
    cLenContainerName: u32,
    pcActualLenContainerName: ?*u32,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn GetLogFileInformation(
    hLog: ?HANDLE,
    pinfoBuffer: ?*CLS_INFORMATION,
    cbBuffer: ?*u32,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn GetLogIoStatistics(
    hLog: ?HANDLE,
    pvStatsBuffer: ?*anyopaque,
    cbStatsBuffer: u32,
    eStatsClass: CLFS_IOSTATS_CLASS,
    pcbStatsWritten: ?*u32,
) callconv(.winapi) BOOL;

pub extern "clfsw32" fn GetLogReservationInfo(
    pvMarshal: ?*anyopaque,
    pcbRecordNumber: ?*u32,
    pcbUserReservation: ?*i64,
    pcbCommitReservation: ?*i64,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn GetNextLogArchiveExtent(
    pvArchiveContext: ?*anyopaque,
    rgadExtent: ?*CLS_ARCHIVE_DESCRIPTOR,
    cDescriptors: u32,
    pcDescriptorsReturned: ?*u32,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn HandleLogFull(
    hLog: ?HANDLE,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn InstallLogPolicy(
    hLog: ?HANDLE,
    pPolicy: ?*CLFS_MGMT_POLICY,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn LogTailAdvanceFailure(
    hLog: ?HANDLE,
    dwReason: u32,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn LsnBlockOffset(
    plsn: ?*const CLS_LSN,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn LsnContainer(
    plsn: ?*const CLS_LSN,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn LsnCreate(
    cidContainer: u32,
    offBlock: u32,
    cRecord: u32,
) callconv(.winapi) CLS_LSN;

pub extern "clfsw32" fn LsnEqual(
    plsn1: ?*const CLS_LSN,
    plsn2: ?*const CLS_LSN,
) callconv(.winapi) BOOLEAN;

pub extern "clfsw32" fn LsnGreater(
    plsn1: ?*const CLS_LSN,
    plsn2: ?*const CLS_LSN,
) callconv(.winapi) BOOLEAN;

pub extern "clfsw32" fn LsnIncrement(
    plsn: ?*CLS_LSN,
) callconv(.winapi) CLS_LSN;

pub extern "clfsw32" fn LsnInvalid(
    plsn: ?*const CLS_LSN,
) callconv(.winapi) BOOLEAN;

pub extern "clfsw32" fn LsnLess(
    plsn1: ?*const CLS_LSN,
    plsn2: ?*const CLS_LSN,
) callconv(.winapi) BOOLEAN;

pub extern "clfsw32" fn LsnNull(
    plsn: ?*const CLS_LSN,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn LsnRecordSequence(
    plsn: ?*const CLS_LSN,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn PrepareLogArchive(
    hLog: ?HANDLE,
    pszBaseLogFileName: [*:0]u16,
    cLen: u32,
    plsnLow: ?*const CLS_LSN,
    plsnHigh: ?*const CLS_LSN,
    pcActualLength: ?*u32,
    poffBaseLogFileData: ?*u64,
    pcbBaseLogFileLength: ?*u64,
    plsnBase: ?*CLS_LSN,
    plsnLast: ?*CLS_LSN,
    plsnCurrentArchiveTail: ?*CLS_LSN,
    ppvArchiveContext: ?*?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn QueryLogPolicy(
    hLog: ?HANDLE,
    ePolicyType: CLFS_MGMT_POLICY_TYPE,
    pPolicyBuffer: ?*CLFS_MGMT_POLICY,
    pcbPolicyBuffer: ?*u32,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn ReadLogArchiveMetadata(
    pvArchiveContext: ?*anyopaque,
    cbOffset: u32,
    cbBytesToRead: u32,
    pbReadBuffer: ?*u8,
    pcbBytesRead: ?*u32,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn ReadLogNotification(
    hLog: ?HANDLE,
    pNotification: ?*CLFS_MGMT_NOTIFICATION,
    lpOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn ReadLogRecord(
    pvMarshal: ?*anyopaque,
    plsnFirst: ?*CLS_LSN,
    eContextMode: CLFS_CONTEXT_MODE,
    ppvReadBuffer: ?*?*anyopaque,
    pcbReadBuffer: ?*u32,
    peRecordType: ?*u8,
    plsnUndoNext: ?*CLS_LSN,
    plsnPrevious: ?*CLS_LSN,
    ppvReadContext: ?*?*anyopaque,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn ReadLogRestartArea(
    pvMarshal: ?*anyopaque,
    ppvRestartBuffer: ?*?*anyopaque,
    pcbRestartBuffer: ?*u32,
    plsn: ?*CLS_LSN,
    ppvContext: ?*?*anyopaque,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn ReadNextLogRecord(
    pvReadContext: ?*anyopaque,
    ppvBuffer: ?*?*anyopaque,
    pcbBuffer: ?*u32,
    peRecordType: ?*u8,
    plsnUser: ?*CLS_LSN,
    plsnUndoNext: ?*CLS_LSN,
    plsnPrevious: ?*CLS_LSN,
    plsnRecord: ?*CLS_LSN,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn ReadPreviousLogRestartArea(
    pvReadContext: ?*anyopaque,
    ppvRestartBuffer: ?*?*anyopaque,
    pcbRestartBuffer: ?*u32,
    plsnRestart: ?*CLS_LSN,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn RegisterForLogWriteNotification(
    hLog: ?HANDLE,
    cbThreshold: u32,
    fEnable: BOOL,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn RegisterManageableLogClient(
    hLog: ?HANDLE,
    pCallbacks: ?*LOG_MANAGEMENT_CALLBACKS,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn RemoveLogContainer(
    hLog: ?HANDLE,
    pwszContainerPath: ?[*:0]u16,
    fForce: BOOL,
    pReserved: ?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn RemoveLogContainerSet(
    hLog: ?HANDLE,
    cContainer: u16,
    rgwszContainerPath: [*]?[*:0]u16,
    fForce: BOOL,
    pReserved: ?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn RemoveLogPolicy(
    hLog: ?HANDLE,
    ePolicyType: CLFS_MGMT_POLICY_TYPE,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn ReserveAndAppendLog(
    pvMarshal: ?*anyopaque,
    rgWriteEntries: ?*CLS_WRITE_ENTRY,
    cWriteEntries: u32,
    plsnUndoNext: ?*CLS_LSN,
    plsnPrevious: ?*CLS_LSN,
    cReserveRecords: u32,
    rgcbReservation: ?*i64,
    fFlags: CLFS_FLAG,
    plsn: ?*CLS_LSN,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn ReserveAndAppendLogAligned(
    pvMarshal: ?*anyopaque,
    rgWriteEntries: ?*CLS_WRITE_ENTRY,
    cWriteEntries: u32,
    cbEntryAlignment: u32,
    plsnUndoNext: ?*CLS_LSN,
    plsnPrevious: ?*CLS_LSN,
    cReserveRecords: u32,
    rgcbReservation: ?*i64,
    fFlags: CLFS_FLAG,
    plsn: ?*CLS_LSN,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn ScanLogContainers(
    pcxScan: ?*CLS_SCAN_CONTEXT,
    eScanMode: u8,
    pReserved: ?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn SetEndOfLog(
    hLog: ?HANDLE,
    plsnEnd: ?*CLS_LSN,
    lpOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn SetLogArchiveMode(
    hLog: ?HANDLE,
    eMode: CLFS_LOG_ARCHIVE_MODE,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn SetLogArchiveTail(
    hLog: ?HANDLE,
    plsnArchiveTail: ?*CLS_LSN,
    pReserved: ?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn SetLogFileSizeWithPolicy(
    hLog: ?HANDLE,
    pDesiredSize: ?*u64,
    pResultingSize: ?*u64,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn TerminateLogArchive(
    pvArchiveContext: ?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn TerminateReadLog(
    pvCursorContext: ?*anyopaque,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn TruncateLog(
    pvMarshal: ?*anyopaque,
    plsnEnd: ?*CLS_LSN,
    lpOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn ValidateLog(
    pszLogFileName: ?[*:0]const u16,
    psaLogFile: ?*SECURITY_ATTRIBUTES,
    pinfoBuffer: ?*CLS_INFORMATION,
    pcbBuffer: ?*u32,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "clfsw32" fn WriteLogRestartArea(
    pvMarshal: ?*anyopaque,
    pvRestartBuffer: ?*anyopaque,
    cbRestartBuffer: u32,
    plsnBase: ?*CLS_LSN,
    fFlags: CLFS_FLAG,
    pcbWritten: ?*u32,
    plsnNext: ?*CLS_LSN,
    pOverlapped: ?*OVERLAPPED,
) callconv(.winapi) BOOL;


//--------------------------------------------------------------------------------
// Section: Imports (24)
//--------------------------------------------------------------------------------
const BOOL = i32;
const BOOLEAN = u8;
const CLFS_BLOCK_ALLOCATION = @import("../win32/storage/file_system.zig").CLFS_BLOCK_ALLOCATION;
const CLFS_BLOCK_DEALLOCATION = @import("../win32/storage/file_system.zig").CLFS_BLOCK_DEALLOCATION;
const CLFS_CONTEXT_MODE = @import("../win32/storage/file_system.zig").CLFS_CONTEXT_MODE;
const CLFS_FLAG = @import("../win32/storage/file_system.zig").CLFS_FLAG;
const CLFS_IOSTATS_CLASS = @import("../win32/storage/file_system.zig").CLFS_IOSTATS_CLASS;
const CLFS_LOG_ARCHIVE_MODE = @import("../win32/storage/file_system.zig").CLFS_LOG_ARCHIVE_MODE;
const CLFS_MGMT_NOTIFICATION = @import("../win32/storage/file_system.zig").CLFS_MGMT_NOTIFICATION;
const CLFS_MGMT_POLICY = @import("../win32/storage/file_system.zig").CLFS_MGMT_POLICY;
const CLFS_MGMT_POLICY_TYPE = @import("../win32/storage/file_system.zig").CLFS_MGMT_POLICY_TYPE;
const CLS_ARCHIVE_DESCRIPTOR = @import("../win32/storage/file_system.zig").CLS_ARCHIVE_DESCRIPTOR;
const CLS_INFORMATION = @import("../win32/storage/file_system.zig").CLS_INFORMATION;
const CLS_LSN = @import("../win32/storage/file_system.zig").CLS_LSN;
const CLS_SCAN_CONTEXT = @import("../win32/storage/file_system.zig").CLS_SCAN_CONTEXT;
const CLS_WRITE_ENTRY = @import("../win32/storage/file_system.zig").CLS_WRITE_ENTRY;
const FILE_ACCESS_FLAGS = @import("../win32/storage/file_system.zig").FILE_ACCESS_FLAGS;
const FILE_CREATION_DISPOSITION = @import("../win32/storage/file_system.zig").FILE_CREATION_DISPOSITION;
const FILE_FLAGS_AND_ATTRIBUTES = @import("../win32/storage/file_system.zig").FILE_FLAGS_AND_ATTRIBUTES;
const FILE_SHARE_MODE = @import("../win32/storage/file_system.zig").FILE_SHARE_MODE;
const HANDLE = @import("../win32/foundation.zig").HANDLE;
const LOG_MANAGEMENT_CALLBACKS = @import("../win32/storage/file_system.zig").LOG_MANAGEMENT_CALLBACKS;
const OVERLAPPED = @import("../win32/system/io.zig").OVERLAPPED;
const SECURITY_ATTRIBUTES = @import("../win32/security.zig").SECURITY_ATTRIBUTES;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
