//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (4)
//--------------------------------------------------------------------------------
pub extern "compstui" fn CommonPropertySheetUIA(
    hWndOwner: ?HWND,
    pfnPropSheetUI: ?PFNPROPSHEETUI,
    lParam: LPARAM,
    pResult: ?*u32,
) callconv(.winapi) i32;

pub extern "compstui" fn CommonPropertySheetUIW(
    hWndOwner: ?HWND,
    pfnPropSheetUI: ?PFNPROPSHEETUI,
    lParam: LPARAM,
    pResult: ?*u32,
) callconv(.winapi) i32;

pub extern "compstui" fn GetCPSUIUserData(
    hDlg: ?HWND,
) callconv(.winapi) usize;

pub extern "compstui" fn SetCPSUIUserData(
    hDlg: ?HWND,
    CPSUIUserData: usize,
) callconv(.winapi) BOOL;


//--------------------------------------------------------------------------------
// Section: Imports (4)
//--------------------------------------------------------------------------------
const BOOL = i32;
const HWND = @import("../win32/foundation.zig").HWND;
const LPARAM = isize;
const PFNPROPSHEETUI = @import("../win32/graphics/printing.zig").PFNPROPSHEETUI;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
