//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (41)
//--------------------------------------------------------------------------------
pub extern "computenetwork" fn HcnCloseEndpoint(
    Endpoint: ?*anyopaque,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnCloseGuestNetworkService(
    GuestNetworkService: ?*anyopaque,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnCloseLoadBalancer(
    LoadBalancer: ?*anyopaque,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnCloseNamespace(
    Namespace: ?*anyopaque,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnCloseNetwork(
    Network: ?*anyopaque,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnCreateEndpoint(
    Network: ?*anyopaque,
    Id: ?*const Guid,
    Settings: ?[*:0]const u16,
    Endpoint: ?*?*anyopaque,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnCreateGuestNetworkService(
    Id: ?*const Guid,
    Settings: ?[*:0]const u16,
    GuestNetworkService: ?*?*anyopaque,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnCreateLoadBalancer(
    Id: ?*const Guid,
    Settings: ?[*:0]const u16,
    LoadBalancer: ?*?*anyopaque,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnCreateNamespace(
    Id: ?*const Guid,
    Settings: ?[*:0]const u16,
    Namespace: ?*?*anyopaque,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnCreateNetwork(
    Id: ?*const Guid,
    Settings: ?[*:0]const u16,
    Network: ?*?*anyopaque,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnDeleteEndpoint(
    Id: ?*const Guid,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnDeleteGuestNetworkService(
    Id: ?*const Guid,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnDeleteLoadBalancer(
    Id: ?*const Guid,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnDeleteNamespace(
    Id: ?*const Guid,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnDeleteNetwork(
    Id: ?*const Guid,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnEnumerateEndpoints(
    Query: ?[*:0]const u16,
    Endpoints: ?*?[*:0]u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnEnumerateGuestNetworkPortReservations(
    ReturnCount: ?*u32,
    /// parameter "ReturnCount" is the size in bytes
    PortEntries: ?*?*HCN_PORT_RANGE_ENTRY,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnEnumerateLoadBalancers(
    Query: ?[*:0]const u16,
    LoadBalancer: ?*?[*:0]u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnEnumerateNamespaces(
    Query: ?[*:0]const u16,
    Namespaces: ?*?[*:0]u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnEnumerateNetworks(
    Query: ?[*:0]const u16,
    Networks: ?*?[*:0]u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnFreeGuestNetworkPortReservations(
    PortEntries: ?*HCN_PORT_RANGE_ENTRY,
) callconv(.winapi) void;

pub extern "computenetwork" fn HcnModifyEndpoint(
    Endpoint: ?*anyopaque,
    Settings: ?[*:0]const u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnModifyGuestNetworkService(
    GuestNetworkService: ?*anyopaque,
    Settings: ?[*:0]const u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnModifyLoadBalancer(
    LoadBalancer: ?*anyopaque,
    Settings: ?[*:0]const u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnModifyNamespace(
    Namespace: ?*anyopaque,
    Settings: ?[*:0]const u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnModifyNetwork(
    Network: ?*anyopaque,
    Settings: ?[*:0]const u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnOpenEndpoint(
    Id: ?*const Guid,
    Endpoint: ?*?*anyopaque,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnOpenLoadBalancer(
    Id: ?*const Guid,
    LoadBalancer: ?*?*anyopaque,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnOpenNamespace(
    Id: ?*const Guid,
    Namespace: ?*?*anyopaque,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnOpenNetwork(
    Id: ?*const Guid,
    Network: ?*?*anyopaque,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnQueryEndpointProperties(
    Endpoint: ?*anyopaque,
    Query: ?[*:0]const u16,
    Properties: ?*?[*:0]u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnQueryLoadBalancerProperties(
    LoadBalancer: ?*anyopaque,
    Query: ?[*:0]const u16,
    Properties: ?*?[*:0]u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnQueryNamespaceProperties(
    Namespace: ?*anyopaque,
    Query: ?[*:0]const u16,
    Properties: ?*?[*:0]u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnQueryNetworkProperties(
    Network: ?*anyopaque,
    Query: ?[*:0]const u16,
    Properties: ?*?[*:0]u16,
    ErrorRecord: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnRegisterGuestNetworkServiceCallback(
    GuestNetworkService: ?*anyopaque,
    Callback: ?HCN_NOTIFICATION_CALLBACK,
    Context: ?*anyopaque,
    CallbackHandle: ?*?*anyopaque,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnRegisterServiceCallback(
    Callback: ?HCN_NOTIFICATION_CALLBACK,
    Context: ?*anyopaque,
    CallbackHandle: ?*?*anyopaque,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnReleaseGuestNetworkServicePortReservationHandle(
    PortReservationHandle: ?HANDLE,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnReserveGuestNetworkServicePort(
    GuestNetworkService: ?*anyopaque,
    Protocol: HCN_PORT_PROTOCOL,
    Access: HCN_PORT_ACCESS,
    Port: u16,
    PortReservationHandle: ?*?HANDLE,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnReserveGuestNetworkServicePortRange(
    GuestNetworkService: ?*anyopaque,
    PortCount: u16,
    PortRangeReservation: ?*HCN_PORT_RANGE_RESERVATION,
    PortReservationHandle: ?*?HANDLE,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnUnregisterGuestNetworkServiceCallback(
    CallbackHandle: ?*anyopaque,
) callconv(.winapi) HRESULT;

pub extern "computenetwork" fn HcnUnregisterServiceCallback(
    CallbackHandle: ?*anyopaque,
) callconv(.winapi) HRESULT;


//--------------------------------------------------------------------------------
// Section: Imports (8)
//--------------------------------------------------------------------------------
const Guid = @import("../win32/zig.zig").Guid;
const HANDLE = @import("../win32/foundation.zig").HANDLE;
const HCN_NOTIFICATION_CALLBACK = @import("../win32/system/host_compute_network.zig").HCN_NOTIFICATION_CALLBACK;
const HCN_PORT_ACCESS = @import("../win32/system/host_compute_network.zig").HCN_PORT_ACCESS;
const HCN_PORT_PROTOCOL = @import("../win32/system/host_compute_network.zig").HCN_PORT_PROTOCOL;
const HCN_PORT_RANGE_ENTRY = @import("../win32/system/host_compute_network.zig").HCN_PORT_RANGE_ENTRY;
const HCN_PORT_RANGE_RESERVATION = @import("../win32/system/host_compute_network.zig").HCN_PORT_RANGE_RESERVATION;
const HRESULT = @import("../win32/zig.zig").HRESULT;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
