//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (60)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsAcquireContextHandle_A(
    CredentialFlags: u32,
    Credentials: ?*anyopaque,
    pContext: ?*DnsContextHandle,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsAcquireContextHandle_W(
    CredentialFlags: u32,
    Credentials: ?*anyopaque,
    pContext: ?*DnsContextHandle,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows8.0'
pub extern "dnsapi" fn DnsCancelQuery(
    pCancelHandle: ?*DNS_QUERY_CANCEL,
) callconv(.winapi) i32;

pub extern "dnsapi" fn DnsConnectionDeletePolicyEntries(
    PolicyEntryTag: DNS_CONNECTION_POLICY_TAG,
) callconv(.winapi) u32;

pub extern "dnsapi" fn DnsConnectionDeleteProxyInfo(
    pwszConnectionName: ?[*:0]const u16,
    Type: DNS_CONNECTION_PROXY_TYPE,
) callconv(.winapi) u32;

pub extern "dnsapi" fn DnsConnectionFreeNameList(
    pNameList: ?*DNS_CONNECTION_NAME_LIST,
) callconv(.winapi) void;

pub extern "dnsapi" fn DnsConnectionFreeProxyInfo(
    pProxyInfo: ?*DNS_CONNECTION_PROXY_INFO,
) callconv(.winapi) void;

pub extern "dnsapi" fn DnsConnectionFreeProxyInfoEx(
    pProxyInfoEx: ?*DNS_CONNECTION_PROXY_INFO_EX,
) callconv(.winapi) void;

pub extern "dnsapi" fn DnsConnectionFreeProxyList(
    pProxyList: ?*DNS_CONNECTION_PROXY_LIST,
) callconv(.winapi) void;

pub extern "dnsapi" fn DnsConnectionGetNameList(
    pNameList: ?*DNS_CONNECTION_NAME_LIST,
) callconv(.winapi) u32;

pub extern "dnsapi" fn DnsConnectionGetProxyInfo(
    pwszConnectionName: ?[*:0]const u16,
    Type: DNS_CONNECTION_PROXY_TYPE,
    pProxyInfo: ?*DNS_CONNECTION_PROXY_INFO,
) callconv(.winapi) u32;

pub extern "dnsapi" fn DnsConnectionGetProxyInfoForHostUrl(
    pwszHostUrl: ?[*:0]const u16,
    pSelectionContext: ?[*:0]u8,
    dwSelectionContextLength: u32,
    dwExplicitInterfaceIndex: u32,
    pProxyInfoEx: ?*DNS_CONNECTION_PROXY_INFO_EX,
) callconv(.winapi) u32;

pub extern "dnsapi" fn DnsConnectionGetProxyList(
    pwszConnectionName: ?[*:0]const u16,
    pProxyList: ?*DNS_CONNECTION_PROXY_LIST,
) callconv(.winapi) u32;

pub extern "dnsapi" fn DnsConnectionSetPolicyEntries(
    PolicyEntryTag: DNS_CONNECTION_POLICY_TAG,
    pPolicyEntryList: ?*DNS_CONNECTION_POLICY_ENTRY_LIST,
) callconv(.winapi) u32;

pub extern "dnsapi" fn DnsConnectionSetProxyInfo(
    pwszConnectionName: ?[*:0]const u16,
    Type: DNS_CONNECTION_PROXY_TYPE,
    pProxyInfo: ?*const DNS_CONNECTION_PROXY_INFO,
) callconv(.winapi) u32;

pub extern "dnsapi" fn DnsConnectionUpdateIfIndexTable(
    pConnectionIfIndexEntries: ?*DNS_CONNECTION_IFINDEX_LIST,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsExtractRecordsFromMessage_UTF8(
    pDnsBuffer: ?*DNS_MESSAGE_BUFFER,
    wMessageLength: u16,
    ppRecord: ?*?*DNS_RECORDA,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsExtractRecordsFromMessage_W(
    pDnsBuffer: ?*DNS_MESSAGE_BUFFER,
    wMessageLength: u16,
    ppRecord: ?*?*DNS_RECORDA,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "dnsapi" fn DnsFree(
    pData: ?*anyopaque,
    FreeType: DNS_FREE_TYPE,
) callconv(.winapi) void;

pub extern "dnsapi" fn DnsFreeCustomServers(
    pcServers: ?*u32,
    ppServers: ?*?*DNS_CUSTOM_SERVER,
) callconv(.winapi) void;

// TODO: this type is limited to platform 'windows6.1'
pub extern "dnsapi" fn DnsFreeProxyName(
    proxyName: ?[*:0]u16,
) callconv(.winapi) void;

pub extern "dnsapi" fn DnsGetApplicationSettings(
    pcServers: ?*u32,
    ppDefaultServers: ?*?*DNS_CUSTOM_SERVER,
    pSettings: ?*DNS_APPLICATION_SETTINGS,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.1'
pub extern "dnsapi" fn DnsGetProxyInformation(
    hostName: ?[*:0]const u16,
    proxyInformation: ?*DNS_PROXY_INFORMATION,
    defaultProxyInformation: ?*DNS_PROXY_INFORMATION,
    completionRoutine: ?DNS_PROXY_COMPLETION_ROUTINE,
    completionContext: ?*anyopaque,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsModifyRecordsInSet_A(
    pAddRecords: ?*DNS_RECORDA,
    pDeleteRecords: ?*DNS_RECORDA,
    Options: u32,
    hCredentials: ?HANDLE,
    pExtraList: ?*anyopaque,
    pReserved: ?*anyopaque,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsModifyRecordsInSet_UTF8(
    pAddRecords: ?*DNS_RECORDA,
    pDeleteRecords: ?*DNS_RECORDA,
    Options: u32,
    hCredentials: ?HANDLE,
    pExtraList: ?*anyopaque,
    pReserved: ?*anyopaque,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsModifyRecordsInSet_W(
    pAddRecords: ?*DNS_RECORDA,
    pDeleteRecords: ?*DNS_RECORDA,
    Options: u32,
    hCredentials: ?HANDLE,
    pExtraList: ?*anyopaque,
    pReserved: ?*anyopaque,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsNameCompare_A(
    pName1: ?[*:0]const u8,
    pName2: ?[*:0]const u8,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsNameCompare_W(
    pName1: ?[*:0]const u16,
    pName2: ?[*:0]const u16,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsQuery_A(
    pszName: ?[*:0]const u8,
    wType: DNS_TYPE,
    Options: DNS_QUERY_OPTIONS,
    pExtra: ?*anyopaque,
    ppQueryResults: ?*?*DNS_RECORDA,
    pReserved: ?*?*anyopaque,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsQuery_UTF8(
    pszName: ?[*:0]const u8,
    wType: DNS_TYPE,
    Options: DNS_QUERY_OPTIONS,
    pExtra: ?*anyopaque,
    ppQueryResults: ?*?*DNS_RECORDA,
    pReserved: ?*?*anyopaque,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsQuery_W(
    pszName: ?[*:0]const u16,
    wType: DNS_TYPE,
    Options: DNS_QUERY_OPTIONS,
    pExtra: ?*anyopaque,
    ppQueryResults: ?*?*DNS_RECORDA,
    pReserved: ?*?*anyopaque,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsQueryConfig(
    Config: DNS_CONFIG_TYPE,
    Flag: u32,
    pwsAdapterName: ?[*:0]const u16,
    pReserved: ?*anyopaque,
    /// parameter "pBufLen" is the size in bytes
    pBuffer: ?*anyopaque,
    pBufLen: ?*u32,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows8.0'
pub extern "dnsapi" fn DnsQueryEx(
    pQueryRequest: ?*DNS_QUERY_REQUEST,
    pQueryResults: ?*DNS_QUERY_RESULT,
    pCancelHandle: ?*DNS_QUERY_CANCEL,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsRecordCompare(
    pRecord1: ?*DNS_RECORDA,
    pRecord2: ?*DNS_RECORDA,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsRecordCopyEx(
    pRecord: ?*DNS_RECORDA,
    CharSetIn: DNS_CHARSET,
    CharSetOut: DNS_CHARSET,
) callconv(.winapi) ?*DNS_RECORDA;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsRecordSetCompare(
    pRR1: ?*DNS_RECORDA,
    pRR2: ?*DNS_RECORDA,
    ppDiff1: ?*?*DNS_RECORDA,
    ppDiff2: ?*?*DNS_RECORDA,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsRecordSetCopyEx(
    pRecordSet: ?*DNS_RECORDA,
    CharSetIn: DNS_CHARSET,
    CharSetOut: DNS_CHARSET,
) callconv(.winapi) ?*DNS_RECORDA;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsRecordSetDetach(
    pRecordList: ?*DNS_RECORDA,
) callconv(.winapi) ?*DNS_RECORDA;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsReleaseContextHandle(
    hContext: ?HANDLE,
) callconv(.winapi) void;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsReplaceRecordSetA(
    pReplaceSet: ?*DNS_RECORDA,
    Options: u32,
    hContext: ?HANDLE,
    pExtraInfo: ?*anyopaque,
    pReserved: ?*anyopaque,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsReplaceRecordSetUTF8(
    pReplaceSet: ?*DNS_RECORDA,
    Options: u32,
    hContext: ?HANDLE,
    pExtraInfo: ?*anyopaque,
    pReserved: ?*anyopaque,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsReplaceRecordSetW(
    pReplaceSet: ?*DNS_RECORDA,
    Options: u32,
    hContext: ?HANDLE,
    pExtraInfo: ?*anyopaque,
    pReserved: ?*anyopaque,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsServiceBrowse(
    pRequest: ?*DNS_SERVICE_BROWSE_REQUEST,
    pCancel: ?*DNS_SERVICE_CANCEL,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsServiceBrowseCancel(
    pCancelHandle: ?*DNS_SERVICE_CANCEL,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsServiceConstructInstance(
    pServiceName: ?[*:0]const u16,
    pHostName: ?[*:0]const u16,
    pIp4: ?*u32,
    pIp6: ?*IP6_ADDRESS,
    wPort: u16,
    wPriority: u16,
    wWeight: u16,
    dwPropertiesCount: u32,
    keys: [*]?[*:0]u16,
    values: [*]?[*:0]u16,
) callconv(.winapi) ?*DNS_SERVICE_INSTANCE;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsServiceCopyInstance(
    pOrig: ?*DNS_SERVICE_INSTANCE,
) callconv(.winapi) ?*DNS_SERVICE_INSTANCE;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsServiceDeRegister(
    pRequest: ?*DNS_SERVICE_REGISTER_REQUEST,
    pCancel: ?*DNS_SERVICE_CANCEL,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsServiceFreeInstance(
    pInstance: ?*DNS_SERVICE_INSTANCE,
) callconv(.winapi) void;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsServiceRegister(
    pRequest: ?*DNS_SERVICE_REGISTER_REQUEST,
    pCancel: ?*DNS_SERVICE_CANCEL,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsServiceRegisterCancel(
    pCancelHandle: ?*DNS_SERVICE_CANCEL,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsServiceResolve(
    pRequest: ?*DNS_SERVICE_RESOLVE_REQUEST,
    pCancel: ?*DNS_SERVICE_CANCEL,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsServiceResolveCancel(
    pCancelHandle: ?*DNS_SERVICE_CANCEL,
) callconv(.winapi) i32;

pub extern "dnsapi" fn DnsSetApplicationSettings(
    cServers: u32,
    pServers: [*]const DNS_CUSTOM_SERVER,
    pSettings: ?*const DNS_APPLICATION_SETTINGS,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsStartMulticastQuery(
    pQueryRequest: ?*MDNS_QUERY_REQUEST,
    pHandle: ?*MDNS_QUERY_HANDLE,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows10.0.10240'
pub extern "dnsapi" fn DnsStopMulticastQuery(
    pHandle: ?*MDNS_QUERY_HANDLE,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsValidateName_A(
    pszName: ?[*:0]const u8,
    Format: DNS_NAME_FORMAT,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsValidateName_UTF8(
    pszName: ?[*:0]const u8,
    Format: DNS_NAME_FORMAT,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsValidateName_W(
    pszName: ?[*:0]const u16,
    Format: DNS_NAME_FORMAT,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsWriteQuestionToBuffer_UTF8(
    pDnsBuffer: ?*DNS_MESSAGE_BUFFER,
    pdwBufferSize: ?*u32,
    pszName: ?[*:0]const u8,
    wType: u16,
    Xid: u16,
    fRecursionDesired: BOOL,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows5.0'
pub extern "dnsapi" fn DnsWriteQuestionToBuffer_W(
    pDnsBuffer: ?*DNS_MESSAGE_BUFFER,
    pdwBufferSize: ?*u32,
    pszName: ?[*:0]const u16,
    wType: u16,
    Xid: u16,
    fRecursionDesired: BOOL,
) callconv(.winapi) BOOL;


//--------------------------------------------------------------------------------
// Section: Imports (35)
//--------------------------------------------------------------------------------
const BOOL = i32;
const DNS_APPLICATION_SETTINGS = @import("../win32/network_management/dns.zig").DNS_APPLICATION_SETTINGS;
const DNS_CHARSET = @import("../win32/network_management/dns.zig").DNS_CHARSET;
const DNS_CONFIG_TYPE = @import("../win32/network_management/dns.zig").DNS_CONFIG_TYPE;
const DNS_CONNECTION_IFINDEX_LIST = @import("../win32/network_management/dns.zig").DNS_CONNECTION_IFINDEX_LIST;
const DNS_CONNECTION_NAME_LIST = @import("../win32/network_management/dns.zig").DNS_CONNECTION_NAME_LIST;
const DNS_CONNECTION_POLICY_ENTRY_LIST = @import("../win32/network_management/dns.zig").DNS_CONNECTION_POLICY_ENTRY_LIST;
const DNS_CONNECTION_POLICY_TAG = @import("../win32/network_management/dns.zig").DNS_CONNECTION_POLICY_TAG;
const DNS_CONNECTION_PROXY_INFO = @import("../win32/network_management/dns.zig").DNS_CONNECTION_PROXY_INFO;
const DNS_CONNECTION_PROXY_INFO_EX = @import("../win32/network_management/dns.zig").DNS_CONNECTION_PROXY_INFO_EX;
const DNS_CONNECTION_PROXY_LIST = @import("../win32/network_management/dns.zig").DNS_CONNECTION_PROXY_LIST;
const DNS_CONNECTION_PROXY_TYPE = @import("../win32/network_management/dns.zig").DNS_CONNECTION_PROXY_TYPE;
const DNS_CUSTOM_SERVER = @import("../win32/network_management/dns.zig").DNS_CUSTOM_SERVER;
const DNS_FREE_TYPE = @import("../win32/network_management/dns.zig").DNS_FREE_TYPE;
const DNS_MESSAGE_BUFFER = @import("../win32/network_management/dns.zig").DNS_MESSAGE_BUFFER;
const DNS_NAME_FORMAT = @import("../win32/network_management/dns.zig").DNS_NAME_FORMAT;
const DNS_PROXY_COMPLETION_ROUTINE = @import("../win32/network_management/dns.zig").DNS_PROXY_COMPLETION_ROUTINE;
const DNS_PROXY_INFORMATION = @import("../win32/network_management/dns.zig").DNS_PROXY_INFORMATION;
const DNS_QUERY_CANCEL = @import("../win32/network_management/dns.zig").DNS_QUERY_CANCEL;
const DNS_QUERY_OPTIONS = @import("../win32/network_management/dns.zig").DNS_QUERY_OPTIONS;
const DNS_QUERY_REQUEST = @import("../win32/network_management/dns.zig").DNS_QUERY_REQUEST;
const DNS_QUERY_RESULT = @import("../win32/network_management/dns.zig").DNS_QUERY_RESULT;
const DNS_RECORDA = @import("../win32/network_management/dns.zig").DNS_RECORDA;
const DNS_SERVICE_BROWSE_REQUEST = @import("../win32/network_management/dns.zig").DNS_SERVICE_BROWSE_REQUEST;
const DNS_SERVICE_CANCEL = @import("../win32/network_management/dns.zig").DNS_SERVICE_CANCEL;
const DNS_SERVICE_INSTANCE = @import("../win32/network_management/dns.zig").DNS_SERVICE_INSTANCE;
const DNS_SERVICE_REGISTER_REQUEST = @import("../win32/network_management/dns.zig").DNS_SERVICE_REGISTER_REQUEST;
const DNS_SERVICE_RESOLVE_REQUEST = @import("../win32/network_management/dns.zig").DNS_SERVICE_RESOLVE_REQUEST;
const DNS_TYPE = @import("../win32/network_management/dns.zig").DNS_TYPE;
const DnsContextHandle = @import("../win32/network_management/dns.zig").DnsContextHandle;
const HANDLE = @import("../win32/foundation.zig").HANDLE;
const IP6_ADDRESS = @import("../win32/network_management/dns.zig").IP6_ADDRESS;
const MDNS_QUERY_HANDLE = @import("../win32/network_management/dns.zig").MDNS_QUERY_HANDLE;
const MDNS_QUERY_REQUEST = @import("../win32/network_management/dns.zig").MDNS_QUERY_REQUEST;
const WIN32_ERROR = @import("../win32/foundation.zig").WIN32_ERROR;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
