//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (79)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddIScsiConnectionA(
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
    Reserved: ?*anyopaque,
    InitiatorPortNumber: u32,
    TargetPortal: ?*ISCSI_TARGET_PORTALA,
    SecurityFlags: u64,
    LoginOptions: ?*ISCSI_LOGIN_OPTIONS,
    KeySize: u32,
    Key: ?[*]u8,
    ConnectionId: ?*ISCSI_UNIQUE_SESSION_ID,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddIScsiConnectionW(
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
    Reserved: ?*anyopaque,
    InitiatorPortNumber: u32,
    TargetPortal: ?*ISCSI_TARGET_PORTALW,
    SecurityFlags: u64,
    LoginOptions: ?*ISCSI_LOGIN_OPTIONS,
    KeySize: u32,
    Key: ?[*]u8,
    ConnectionId: ?*ISCSI_UNIQUE_SESSION_ID,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddIScsiSendTargetPortalA(
    InitiatorInstance: ?[*:0]u8,
    InitiatorPortNumber: u32,
    LoginOptions: ?*ISCSI_LOGIN_OPTIONS,
    SecurityFlags: u64,
    Portal: ?*ISCSI_TARGET_PORTALA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddIScsiSendTargetPortalW(
    InitiatorInstance: ?[*:0]u16,
    InitiatorPortNumber: u32,
    LoginOptions: ?*ISCSI_LOGIN_OPTIONS,
    SecurityFlags: u64,
    Portal: ?*ISCSI_TARGET_PORTALW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddIScsiStaticTargetA(
    TargetName: ?[*:0]u8,
    TargetAlias: ?[*:0]u8,
    TargetFlags: u32,
    Persist: BOOLEAN,
    Mappings: ?*ISCSI_TARGET_MAPPINGA,
    LoginOptions: ?*ISCSI_LOGIN_OPTIONS,
    PortalGroup: ?*ISCSI_TARGET_PORTAL_GROUPA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddIScsiStaticTargetW(
    TargetName: ?[*:0]u16,
    TargetAlias: ?[*:0]u16,
    TargetFlags: u32,
    Persist: BOOLEAN,
    Mappings: ?*ISCSI_TARGET_MAPPINGW,
    LoginOptions: ?*ISCSI_LOGIN_OPTIONS,
    PortalGroup: ?*ISCSI_TARGET_PORTAL_GROUPW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddISNSServerA(
    Address: ?[*:0]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddISNSServerW(
    Address: ?[*:0]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddPersistentIScsiDeviceA(
    DevicePath: ?[*:0]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddPersistentIScsiDeviceW(
    DevicePath: ?[*:0]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddRadiusServerA(
    Address: ?[*:0]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn AddRadiusServerW(
    Address: ?[*:0]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ClearPersistentIScsiDevices(
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetDevicesForIScsiSessionA(
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
    DeviceCount: ?*u32,
    Devices: ?*ISCSI_DEVICE_ON_SESSIONA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetDevicesForIScsiSessionW(
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
    DeviceCount: ?*u32,
    Devices: ?*ISCSI_DEVICE_ON_SESSIONW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetIScsiIKEInfoA(
    InitiatorName: ?[*:0]u8,
    InitiatorPortNumber: u32,
    Reserved: ?*u32,
    AuthInfo: ?*IKE_AUTHENTICATION_INFORMATION,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetIScsiIKEInfoW(
    InitiatorName: ?[*:0]u16,
    InitiatorPortNumber: u32,
    Reserved: ?*u32,
    AuthInfo: ?*IKE_AUTHENTICATION_INFORMATION,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetIScsiInitiatorNodeNameA(
    InitiatorNodeName: ?[*]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetIScsiInitiatorNodeNameW(
    InitiatorNodeName: ?[*]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetIScsiSessionListA(
    BufferSize: ?*u32,
    SessionCount: ?*u32,
    SessionInfo: ?*ISCSI_SESSION_INFOA,
) callconv(.winapi) u32;

pub extern "iscsidsc" fn GetIScsiSessionListEx(
    BufferSize: ?*u32,
    SessionCountPtr: ?*u32,
    SessionInfo: ?*ISCSI_SESSION_INFO_EX,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetIScsiSessionListW(
    BufferSize: ?*u32,
    SessionCount: ?*u32,
    SessionInfo: ?*ISCSI_SESSION_INFOW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetIScsiTargetInformationA(
    TargetName: ?[*:0]u8,
    DiscoveryMechanism: ?[*:0]u8,
    InfoClass: TARGET_INFORMATION_CLASS,
    BufferSize: ?*u32,
    Buffer: ?*anyopaque,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetIScsiTargetInformationW(
    TargetName: ?[*:0]u16,
    DiscoveryMechanism: ?[*:0]u16,
    InfoClass: TARGET_INFORMATION_CLASS,
    BufferSize: ?*u32,
    Buffer: ?*anyopaque,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn GetIScsiVersionInformation(
    VersionInfo: ?*ISCSI_VERSION_INFO,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn LoginIScsiTargetA(
    TargetName: ?[*:0]u8,
    IsInformationalSession: BOOLEAN,
    InitiatorInstance: ?[*:0]u8,
    InitiatorPortNumber: u32,
    TargetPortal: ?*ISCSI_TARGET_PORTALA,
    SecurityFlags: u64,
    Mappings: ?*ISCSI_TARGET_MAPPINGA,
    LoginOptions: ?*ISCSI_LOGIN_OPTIONS,
    KeySize: u32,
    Key: ?[*]u8,
    IsPersistent: BOOLEAN,
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
    UniqueConnectionId: ?*ISCSI_UNIQUE_SESSION_ID,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn LoginIScsiTargetW(
    TargetName: ?[*:0]u16,
    IsInformationalSession: BOOLEAN,
    InitiatorInstance: ?[*:0]u16,
    InitiatorPortNumber: u32,
    TargetPortal: ?*ISCSI_TARGET_PORTALW,
    SecurityFlags: u64,
    Mappings: ?*ISCSI_TARGET_MAPPINGW,
    LoginOptions: ?*ISCSI_LOGIN_OPTIONS,
    KeySize: u32,
    Key: ?[*]u8,
    IsPersistent: BOOLEAN,
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
    UniqueConnectionId: ?*ISCSI_UNIQUE_SESSION_ID,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn LogoutIScsiTarget(
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RefreshIScsiSendTargetPortalA(
    InitiatorInstance: ?[*:0]u8,
    InitiatorPortNumber: u32,
    Portal: ?*ISCSI_TARGET_PORTALA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RefreshIScsiSendTargetPortalW(
    InitiatorInstance: ?[*:0]u16,
    InitiatorPortNumber: u32,
    Portal: ?*ISCSI_TARGET_PORTALW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RefreshISNSServerA(
    Address: ?[*:0]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RefreshISNSServerW(
    Address: ?[*:0]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveIScsiConnection(
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
    ConnectionId: ?*ISCSI_UNIQUE_SESSION_ID,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveIScsiPersistentTargetA(
    InitiatorInstance: ?[*:0]u8,
    InitiatorPortNumber: u32,
    TargetName: ?[*:0]u8,
    Portal: ?*ISCSI_TARGET_PORTALA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveIScsiPersistentTargetW(
    InitiatorInstance: ?[*:0]u16,
    InitiatorPortNumber: u32,
    TargetName: ?[*:0]u16,
    Portal: ?*ISCSI_TARGET_PORTALW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveIScsiSendTargetPortalA(
    InitiatorInstance: ?[*:0]u8,
    InitiatorPortNumber: u32,
    Portal: ?*ISCSI_TARGET_PORTALA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveIScsiSendTargetPortalW(
    InitiatorInstance: ?[*:0]u16,
    InitiatorPortNumber: u32,
    Portal: ?*ISCSI_TARGET_PORTALW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveIScsiStaticTargetA(
    TargetName: ?[*:0]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveIScsiStaticTargetW(
    TargetName: ?[*:0]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveISNSServerA(
    Address: ?[*:0]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveISNSServerW(
    Address: ?[*:0]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemovePersistentIScsiDeviceA(
    DevicePath: ?[*:0]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemovePersistentIScsiDeviceW(
    DevicePath: ?[*:0]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveRadiusServerA(
    Address: ?[*:0]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn RemoveRadiusServerW(
    Address: ?[*:0]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportActiveIScsiTargetMappingsA(
    BufferSize: ?*u32,
    MappingCount: ?*u32,
    Mappings: ?*ISCSI_TARGET_MAPPINGA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportActiveIScsiTargetMappingsW(
    BufferSize: ?*u32,
    MappingCount: ?*u32,
    Mappings: ?*ISCSI_TARGET_MAPPINGW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiInitiatorListA(
    BufferSize: ?*u32,
    Buffer: ?[*]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiInitiatorListW(
    BufferSize: ?*u32,
    Buffer: ?[*]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiPersistentLoginsA(
    Count: ?*u32,
    PersistentLoginInfo: ?*PERSISTENT_ISCSI_LOGIN_INFOA,
    BufferSizeInBytes: ?*u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiPersistentLoginsW(
    Count: ?*u32,
    PersistentLoginInfo: ?*PERSISTENT_ISCSI_LOGIN_INFOW,
    BufferSizeInBytes: ?*u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiSendTargetPortalsA(
    PortalCount: ?*u32,
    PortalInfo: ?*ISCSI_TARGET_PORTAL_INFOA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiSendTargetPortalsExA(
    PortalCount: ?*u32,
    PortalInfoSize: ?*u32,
    PortalInfo: ?*ISCSI_TARGET_PORTAL_INFO_EXA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiSendTargetPortalsExW(
    PortalCount: ?*u32,
    PortalInfoSize: ?*u32,
    PortalInfo: ?*ISCSI_TARGET_PORTAL_INFO_EXW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiSendTargetPortalsW(
    PortalCount: ?*u32,
    PortalInfo: ?*ISCSI_TARGET_PORTAL_INFOW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiTargetPortalsA(
    InitiatorName: ?[*:0]u8,
    TargetName: ?[*:0]u8,
    TargetPortalTag: ?*u16,
    ElementCount: ?*u32,
    Portals: ?*ISCSI_TARGET_PORTALA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiTargetPortalsW(
    InitiatorName: ?[*:0]u16,
    TargetName: ?[*:0]u16,
    TargetPortalTag: ?*u16,
    ElementCount: ?*u32,
    Portals: ?*ISCSI_TARGET_PORTALW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiTargetsA(
    ForceUpdate: BOOLEAN,
    BufferSize: ?*u32,
    Buffer: ?[*]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportIScsiTargetsW(
    ForceUpdate: BOOLEAN,
    BufferSize: ?*u32,
    Buffer: ?[*]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportISNSServerListA(
    BufferSizeInChar: ?*u32,
    Buffer: ?[*]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportISNSServerListW(
    BufferSizeInChar: ?*u32,
    Buffer: ?[*]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportPersistentIScsiDevicesA(
    BufferSizeInChar: ?*u32,
    Buffer: ?[*]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportPersistentIScsiDevicesW(
    BufferSizeInChar: ?*u32,
    Buffer: ?[*]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportRadiusServerListA(
    BufferSizeInChar: ?*u32,
    Buffer: ?[*]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn ReportRadiusServerListW(
    BufferSizeInChar: ?*u32,
    Buffer: ?[*]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SendScsiInquiry(
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
    Lun: u64,
    EvpdCmddt: u8,
    PageCode: u8,
    ScsiStatus: ?*u8,
    ResponseSize: ?*u32,
    ResponseBuffer: ?*u8,
    SenseSize: ?*u32,
    SenseBuffer: ?*u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SendScsiReadCapacity(
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
    Lun: u64,
    ScsiStatus: ?*u8,
    ResponseSize: ?*u32,
    ResponseBuffer: ?*u8,
    SenseSize: ?*u32,
    SenseBuffer: ?*u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SendScsiReportLuns(
    UniqueSessionId: ?*ISCSI_UNIQUE_SESSION_ID,
    ScsiStatus: ?*u8,
    ResponseSize: ?*u32,
    ResponseBuffer: ?*u8,
    SenseSize: ?*u32,
    SenseBuffer: ?*u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SetIScsiGroupPresharedKey(
    KeyLength: u32,
    Key: ?*u8,
    Persist: BOOLEAN,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SetIScsiIKEInfoA(
    InitiatorName: ?[*:0]u8,
    InitiatorPortNumber: u32,
    AuthInfo: ?*IKE_AUTHENTICATION_INFORMATION,
    Persist: BOOLEAN,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SetIScsiIKEInfoW(
    InitiatorName: ?[*:0]u16,
    InitiatorPortNumber: u32,
    AuthInfo: ?*IKE_AUTHENTICATION_INFORMATION,
    Persist: BOOLEAN,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SetIScsiInitiatorCHAPSharedSecret(
    SharedSecretLength: u32,
    SharedSecret: ?*u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SetIScsiInitiatorNodeNameA(
    InitiatorNodeName: ?[*:0]u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SetIScsiInitiatorNodeNameW(
    InitiatorNodeName: ?[*:0]u16,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SetIScsiInitiatorRADIUSSharedSecret(
    SharedSecretLength: u32,
    SharedSecret: ?*u8,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SetIScsiTunnelModeOuterAddressA(
    InitiatorName: ?[*:0]u8,
    InitiatorPortNumber: u32,
    DestinationAddress: ?[*:0]u8,
    OuterModeAddress: ?[*:0]u8,
    Persist: BOOLEAN,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SetIScsiTunnelModeOuterAddressW(
    InitiatorName: ?[*:0]u16,
    InitiatorPortNumber: u32,
    DestinationAddress: ?[*:0]u16,
    OuterModeAddress: ?[*:0]u16,
    Persist: BOOLEAN,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "iscsidsc" fn SetupPersistentIScsiDevices(
) callconv(.winapi) u32;

pub extern "iscsidsc" fn SetupPersistentIScsiVolumes(
) callconv(.winapi) u32;


//--------------------------------------------------------------------------------
// Section: Imports (23)
//--------------------------------------------------------------------------------
const BOOLEAN = u8;
const IKE_AUTHENTICATION_INFORMATION = @import("../win32/storage/iscsi_disc.zig").IKE_AUTHENTICATION_INFORMATION;
const ISCSI_DEVICE_ON_SESSIONA = @import("../win32/storage/iscsi_disc.zig").ISCSI_DEVICE_ON_SESSIONA;
const ISCSI_DEVICE_ON_SESSIONW = @import("../win32/storage/iscsi_disc.zig").ISCSI_DEVICE_ON_SESSIONW;
const ISCSI_LOGIN_OPTIONS = @import("../win32/storage/iscsi_disc.zig").ISCSI_LOGIN_OPTIONS;
const ISCSI_SESSION_INFO_EX = @import("../win32/storage/iscsi_disc.zig").ISCSI_SESSION_INFO_EX;
const ISCSI_SESSION_INFOA = @import("../win32/storage/iscsi_disc.zig").ISCSI_SESSION_INFOA;
const ISCSI_SESSION_INFOW = @import("../win32/storage/iscsi_disc.zig").ISCSI_SESSION_INFOW;
const ISCSI_TARGET_MAPPINGA = @import("../win32/storage/iscsi_disc.zig").ISCSI_TARGET_MAPPINGA;
const ISCSI_TARGET_MAPPINGW = @import("../win32/storage/iscsi_disc.zig").ISCSI_TARGET_MAPPINGW;
const ISCSI_TARGET_PORTAL_GROUPA = @import("../win32/storage/iscsi_disc.zig").ISCSI_TARGET_PORTAL_GROUPA;
const ISCSI_TARGET_PORTAL_GROUPW = @import("../win32/storage/iscsi_disc.zig").ISCSI_TARGET_PORTAL_GROUPW;
const ISCSI_TARGET_PORTAL_INFO_EXA = @import("../win32/storage/iscsi_disc.zig").ISCSI_TARGET_PORTAL_INFO_EXA;
const ISCSI_TARGET_PORTAL_INFO_EXW = @import("../win32/storage/iscsi_disc.zig").ISCSI_TARGET_PORTAL_INFO_EXW;
const ISCSI_TARGET_PORTAL_INFOA = @import("../win32/storage/iscsi_disc.zig").ISCSI_TARGET_PORTAL_INFOA;
const ISCSI_TARGET_PORTAL_INFOW = @import("../win32/storage/iscsi_disc.zig").ISCSI_TARGET_PORTAL_INFOW;
const ISCSI_TARGET_PORTALA = @import("../win32/storage/iscsi_disc.zig").ISCSI_TARGET_PORTALA;
const ISCSI_TARGET_PORTALW = @import("../win32/storage/iscsi_disc.zig").ISCSI_TARGET_PORTALW;
const ISCSI_UNIQUE_SESSION_ID = @import("../win32/storage/iscsi_disc.zig").ISCSI_UNIQUE_SESSION_ID;
const ISCSI_VERSION_INFO = @import("../win32/storage/iscsi_disc.zig").ISCSI_VERSION_INFO;
const PERSISTENT_ISCSI_LOGIN_INFOA = @import("../win32/storage/iscsi_disc.zig").PERSISTENT_ISCSI_LOGIN_INFOA;
const PERSISTENT_ISCSI_LOGIN_INFOW = @import("../win32/storage/iscsi_disc.zig").PERSISTENT_ISCSI_LOGIN_INFOW;
const TARGET_INFORMATION_CLASS = @import("../win32/storage/iscsi_disc.zig").TARGET_INFORMATION_CLASS;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
