//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (19)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagGetColorEffect(
    hwnd: ?HWND,
    pEffect: ?*MAGCOLOREFFECT,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows8.0'
pub extern "magnification" fn MagGetFullscreenColorEffect(
    pEffect: ?*MAGCOLOREFFECT,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows8.0'
pub extern "magnification" fn MagGetFullscreenTransform(
    pMagLevel: ?*f32,
    pxOffset: ?*i32,
    pyOffset: ?*i32,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagGetImageScalingCallback(
    hwnd: ?HWND,
) callconv(.winapi) ?MagImageScalingCallback;

// TODO: this type is limited to platform 'windows8.0'
pub extern "magnification" fn MagGetInputTransform(
    pfEnabled: ?*BOOL,
    pRectSource: ?*RECT,
    pRectDest: ?*RECT,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagGetWindowFilterList(
    hwnd: ?HWND,
    pdwFilterMode: ?*MW_FILTERMODE,
    count: i32,
    pHWND: ?*?HWND,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagGetWindowSource(
    hwnd: ?HWND,
    pRect: ?*RECT,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagGetWindowTransform(
    hwnd: ?HWND,
    pTransform: ?*MAGTRANSFORM,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagInitialize(
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagSetColorEffect(
    hwnd: ?HWND,
    pEffect: ?*MAGCOLOREFFECT,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows8.0'
pub extern "magnification" fn MagSetFullscreenColorEffect(
    pEffect: ?*MAGCOLOREFFECT,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows8.0'
pub extern "magnification" fn MagSetFullscreenTransform(
    magLevel: f32,
    xOffset: i32,
    yOffset: i32,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagSetImageScalingCallback(
    hwnd: ?HWND,
    callback: ?MagImageScalingCallback,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows8.0'
pub extern "magnification" fn MagSetInputTransform(
    fEnabled: BOOL,
    pRectSource: ?*const RECT,
    pRectDest: ?*const RECT,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagSetWindowFilterList(
    hwnd: ?HWND,
    dwFilterMode: MW_FILTERMODE,
    count: i32,
    pHWND: ?*?HWND,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagSetWindowSource(
    hwnd: ?HWND,
    rect: RECT,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagSetWindowTransform(
    hwnd: ?HWND,
    pTransform: ?*MAGTRANSFORM,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows8.0'
pub extern "magnification" fn MagShowSystemCursor(
    fShowCursor: BOOL,
) callconv(.winapi) BOOL;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "magnification" fn MagUninitialize(
) callconv(.winapi) BOOL;


//--------------------------------------------------------------------------------
// Section: Imports (7)
//--------------------------------------------------------------------------------
const BOOL = i32;
const HWND = @import("../win32/foundation.zig").HWND;
const MAGCOLOREFFECT = @import("../win32/ui/magnification.zig").MAGCOLOREFFECT;
const MagImageScalingCallback = @import("../win32/ui/magnification.zig").MagImageScalingCallback;
const MAGTRANSFORM = @import("../win32/ui/magnification.zig").MAGTRANSFORM;
const MW_FILTERMODE = @import("../win32/ui/magnification.zig").MW_FILTERMODE;
const RECT = @import("../win32/foundation.zig").RECT;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
