//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (42)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverAddA(
    phadid: ?*isize,
    hinstModule: ?HINSTANCE,
    lParam: LPARAM,
    dwPriority: u32,
    fdwAdd: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverAddW(
    phadid: ?*isize,
    hinstModule: ?HINSTANCE,
    lParam: LPARAM,
    dwPriority: u32,
    fdwAdd: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverClose(
    had: ?HACMDRIVER,
    fdwClose: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverDetailsA(
    hadid: ?HACMDRIVERID,
    padd: ?*ACMDRIVERDETAILSA,
    fdwDetails: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverDetailsW(
    hadid: ?HACMDRIVERID,
    padd: ?*ACMDRIVERDETAILSW,
    fdwDetails: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverEnum(
    fnCallback: ?ACMDRIVERENUMCB,
    dwInstance: usize,
    fdwEnum: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverID(
    hao: ?HACMOBJ,
    phadid: ?*isize,
    fdwDriverID: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverMessage(
    had: ?HACMDRIVER,
    uMsg: u32,
    lParam1: LPARAM,
    lParam2: LPARAM,
) callconv(.winapi) LRESULT;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverOpen(
    phad: ?*isize,
    hadid: ?HACMDRIVERID,
    fdwOpen: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverPriority(
    hadid: ?HACMDRIVERID,
    dwPriority: u32,
    fdwPriority: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmDriverRemove(
    hadid: ?HACMDRIVERID,
    fdwRemove: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFilterChooseA(
    pafltrc: ?*ACMFILTERCHOOSEA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFilterChooseW(
    pafltrc: ?*ACMFILTERCHOOSEW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFilterDetailsA(
    had: ?HACMDRIVER,
    pafd: ?*ACMFILTERDETAILSA,
    fdwDetails: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFilterDetailsW(
    had: ?HACMDRIVER,
    pafd: ?*ACMFILTERDETAILSW,
    fdwDetails: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFilterEnumA(
    had: ?HACMDRIVER,
    pafd: ?*ACMFILTERDETAILSA,
    fnCallback: ?ACMFILTERENUMCBA,
    dwInstance: usize,
    fdwEnum: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFilterEnumW(
    had: ?HACMDRIVER,
    pafd: ?*ACMFILTERDETAILSW,
    fnCallback: ?ACMFILTERENUMCBW,
    dwInstance: usize,
    fdwEnum: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFilterTagDetailsA(
    had: ?HACMDRIVER,
    paftd: ?*ACMFILTERTAGDETAILSA,
    fdwDetails: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFilterTagDetailsW(
    had: ?HACMDRIVER,
    paftd: ?*ACMFILTERTAGDETAILSW,
    fdwDetails: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFilterTagEnumA(
    had: ?HACMDRIVER,
    paftd: ?*ACMFILTERTAGDETAILSA,
    fnCallback: ?ACMFILTERTAGENUMCBA,
    dwInstance: usize,
    fdwEnum: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFilterTagEnumW(
    had: ?HACMDRIVER,
    paftd: ?*ACMFILTERTAGDETAILSW,
    fnCallback: ?ACMFILTERTAGENUMCBW,
    dwInstance: usize,
    fdwEnum: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatChooseA(
    pafmtc: ?*ACMFORMATCHOOSEA,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatChooseW(
    pafmtc: ?*ACMFORMATCHOOSEW,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatDetailsA(
    had: ?HACMDRIVER,
    pafd: ?*ACMFORMATDETAILSA,
    fdwDetails: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatDetailsW(
    had: ?HACMDRIVER,
    pafd: ?*tACMFORMATDETAILSW,
    fdwDetails: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatEnumA(
    had: ?HACMDRIVER,
    pafd: ?*ACMFORMATDETAILSA,
    fnCallback: ?ACMFORMATENUMCBA,
    dwInstance: usize,
    fdwEnum: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatEnumW(
    had: ?HACMDRIVER,
    pafd: ?*tACMFORMATDETAILSW,
    fnCallback: ?ACMFORMATENUMCBW,
    dwInstance: usize,
    fdwEnum: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatSuggest(
    had: ?HACMDRIVER,
    pwfxSrc: ?*WAVEFORMATEX,
    pwfxDst: ?*WAVEFORMATEX,
    cbwfxDst: u32,
    fdwSuggest: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatTagDetailsA(
    had: ?HACMDRIVER,
    paftd: ?*ACMFORMATTAGDETAILSA,
    fdwDetails: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatTagDetailsW(
    had: ?HACMDRIVER,
    paftd: ?*ACMFORMATTAGDETAILSW,
    fdwDetails: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatTagEnumA(
    had: ?HACMDRIVER,
    paftd: ?*ACMFORMATTAGDETAILSA,
    fnCallback: ?ACMFORMATTAGENUMCBA,
    dwInstance: usize,
    fdwEnum: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmFormatTagEnumW(
    had: ?HACMDRIVER,
    paftd: ?*ACMFORMATTAGDETAILSW,
    fnCallback: ?ACMFORMATTAGENUMCBW,
    dwInstance: usize,
    fdwEnum: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmGetVersion(
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmMetrics(
    hao: ?HACMOBJ,
    uMetric: u32,
    pMetric: ?*anyopaque,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmStreamClose(
    has: ?HACMSTREAM,
    fdwClose: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmStreamConvert(
    has: ?HACMSTREAM,
    pash: ?*ACMSTREAMHEADER,
    fdwConvert: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmStreamMessage(
    has: ?HACMSTREAM,
    uMsg: u32,
    lParam1: LPARAM,
    lParam2: LPARAM,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmStreamOpen(
    phas: ?*isize,
    had: ?HACMDRIVER,
    pwfxSrc: ?*WAVEFORMATEX,
    pwfxDst: ?*WAVEFORMATEX,
    pwfltr: ?*WAVEFILTER,
    dwCallback: usize,
    dwInstance: usize,
    fdwOpen: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmStreamPrepareHeader(
    has: ?HACMSTREAM,
    pash: ?*ACMSTREAMHEADER,
    fdwPrepare: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmStreamReset(
    has: ?HACMSTREAM,
    fdwReset: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmStreamSize(
    has: ?HACMSTREAM,
    cbInput: u32,
    pdwOutputBytes: ?*u32,
    fdwSize: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.0'
pub extern "msacm32" fn acmStreamUnprepareHeader(
    has: ?HACMSTREAM,
    pash: ?*ACMSTREAMHEADER,
    fdwUnprepare: u32,
) callconv(.winapi) u32;


//--------------------------------------------------------------------------------
// Section: Imports (33)
//--------------------------------------------------------------------------------
const ACMDRIVERDETAILSA = @import("../win32/media/audio.zig").ACMDRIVERDETAILSA;
const ACMDRIVERDETAILSW = @import("../win32/media/audio.zig").ACMDRIVERDETAILSW;
const ACMDRIVERENUMCB = @import("../win32/media/audio.zig").ACMDRIVERENUMCB;
const ACMFILTERCHOOSEA = @import("../win32/media/audio.zig").ACMFILTERCHOOSEA;
const ACMFILTERCHOOSEW = @import("../win32/media/audio.zig").ACMFILTERCHOOSEW;
const ACMFILTERDETAILSA = @import("../win32/media/audio.zig").ACMFILTERDETAILSA;
const ACMFILTERDETAILSW = @import("../win32/media/audio.zig").ACMFILTERDETAILSW;
const ACMFILTERENUMCBA = @import("../win32/media/audio.zig").ACMFILTERENUMCBA;
const ACMFILTERENUMCBW = @import("../win32/media/audio.zig").ACMFILTERENUMCBW;
const ACMFILTERTAGDETAILSA = @import("../win32/media/audio.zig").ACMFILTERTAGDETAILSA;
const ACMFILTERTAGDETAILSW = @import("../win32/media/audio.zig").ACMFILTERTAGDETAILSW;
const ACMFILTERTAGENUMCBA = @import("../win32/media/audio.zig").ACMFILTERTAGENUMCBA;
const ACMFILTERTAGENUMCBW = @import("../win32/media/audio.zig").ACMFILTERTAGENUMCBW;
const ACMFORMATCHOOSEA = @import("../win32/media/audio.zig").ACMFORMATCHOOSEA;
const ACMFORMATCHOOSEW = @import("../win32/media/audio.zig").ACMFORMATCHOOSEW;
const ACMFORMATDETAILSA = @import("../win32/media/audio.zig").ACMFORMATDETAILSA;
const ACMFORMATENUMCBA = @import("../win32/media/audio.zig").ACMFORMATENUMCBA;
const ACMFORMATENUMCBW = @import("../win32/media/audio.zig").ACMFORMATENUMCBW;
const ACMFORMATTAGDETAILSA = @import("../win32/media/audio.zig").ACMFORMATTAGDETAILSA;
const ACMFORMATTAGDETAILSW = @import("../win32/media/audio.zig").ACMFORMATTAGDETAILSW;
const ACMFORMATTAGENUMCBA = @import("../win32/media/audio.zig").ACMFORMATTAGENUMCBA;
const ACMFORMATTAGENUMCBW = @import("../win32/media/audio.zig").ACMFORMATTAGENUMCBW;
const ACMSTREAMHEADER = @import("../win32/media/audio.zig").ACMSTREAMHEADER;
const HACMDRIVER = @import("../win32/media/audio.zig").HACMDRIVER;
const HACMDRIVERID = @import("../win32/media/audio.zig").HACMDRIVERID;
const HACMOBJ = @import("../win32/media/audio.zig").HACMOBJ;
const HACMSTREAM = @import("../win32/media/audio.zig").HACMSTREAM;
const HINSTANCE = @import("../win32/foundation.zig").HINSTANCE;
const LPARAM = isize;
const LRESULT = isize;
const tACMFORMATDETAILSW = @import("../win32/media/audio.zig").tACMFORMATDETAILSW;
const WAVEFILTER = @import("../win32/media/audio.zig").WAVEFILTER;
const WAVEFORMATEX = @import("../win32/media/audio.zig").WAVEFORMATEX;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
