//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (84)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn CallNtPowerInformation(
    InformationLevel: POWER_INFORMATION_LEVEL,
    /// parameter "InputBufferLength" is the size in bytes
    InputBuffer: ?*anyopaque,
    InputBufferLength: u32,
    /// parameter "OutputBufferLength" is the size in bytes
    OutputBuffer: ?*anyopaque,
    OutputBufferLength: u32,
) callconv(.winapi) NTSTATUS;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn CanUserWritePwrScheme(
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn DeletePwrScheme(
    uiID: u32,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn DevicePowerClose(
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn DevicePowerEnumDevices(
    QueryIndex: u32,
    QueryInterpretationFlags: u32,
    QueryFlags: u32,
    /// parameter "pBufferSize" is the size in bytes
    pReturnBuffer: ?*u8,
    pBufferSize: ?*u32,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn DevicePowerOpen(
    DebugMask: u32,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn DevicePowerSetDeviceState(
    DeviceDescription: ?[*:0]const u16,
    SetFlags: u32,
    SetData: ?*anyopaque,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn EnumPwrSchemes(
    lpfn: ?PWRSCHEMESENUMPROC,
    lParam: LPARAM,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn GetActivePwrScheme(
    puiID: ?*u32,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn GetCurrentPowerPolicies(
    pGlobalPowerPolicy: ?*GLOBAL_POWER_POLICY,
    pPowerPolicy: ?*POWER_POLICY,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn GetPwrCapabilities(
    lpspc: ?*SYSTEM_POWER_CAPABILITIES,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn GetPwrDiskSpindownRange(
    puiMax: ?*u32,
    puiMin: ?*u32,
) callconv(.winapi) BOOLEAN;

pub extern "powrprof" fn IsAdminOverrideActive(
    papp: ?*ADMINISTRATOR_POWER_POLICY,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn IsPwrHibernateAllowed(
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn IsPwrShutdownAllowed(
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn IsPwrSuspendAllowed(
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerCanRestoreIndividualDefaultPowerScheme(
    SchemeGuid: ?*const Guid,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerCreatePossibleSetting(
    RootSystemPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    PossibleSettingIndex: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerCreateSetting(
    RootSystemPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerDeleteScheme(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerDeterminePlatformRole(
) callconv(.winapi) POWER_PLATFORM_ROLE;

// TODO: this type is limited to platform 'windows8.0'
pub extern "powrprof" fn PowerDeterminePlatformRoleEx(
    Version: POWER_PLATFORM_ROLE_VERSION,
) callconv(.winapi) POWER_PLATFORM_ROLE;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerDuplicateScheme(
    RootPowerKey: ?HKEY,
    SourceSchemeGuid: ?*const Guid,
    DestinationSchemeGuid: ?*?*Guid,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerEnumerate(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    AccessFlags: POWER_DATA_ACCESSOR,
    Index: u32,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerGetActiveScheme(
    UserRootPowerKey: ?HKEY,
    ActivePolicyGuid: ?*?*Guid,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerImportPowerScheme(
    RootPowerKey: ?HKEY,
    ImportFileNamePath: ?[*:0]const u16,
    DestinationSchemeGuid: ?*?*Guid,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.1'
pub extern "powrprof" fn PowerIsSettingRangeDefined(
    SubKeyGuid: ?*const Guid,
    SettingGuid: ?*const Guid,
) callconv(.winapi) BOOLEAN;

pub extern "powrprof" fn PowerOpenSystemPowerKey(
    phSystemPowerKey: ?*?HKEY,
    Access: u32,
    OpenExisting: BOOL,
) callconv(.winapi) u32;

pub extern "powrprof" fn PowerOpenUserPowerKey(
    phUserPowerKey: ?*?HKEY,
    Access: u32,
    OpenExisting: BOOL,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadACDefaultIndex(
    RootPowerKey: ?HKEY,
    SchemePersonalityGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    AcDefaultIndex: ?*u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadACValue(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    Type: ?*u32,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadACValueIndex(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    AcValueIndex: ?*u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadDCDefaultIndex(
    RootPowerKey: ?HKEY,
    SchemePersonalityGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    DcDefaultIndex: ?*u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadDCValue(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    Type: ?*u32,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadDCValueIndex(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    DcValueIndex: ?*u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadDescription(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadFriendlyName(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadIconResourceSpecifier(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadPossibleDescription(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    PossibleSettingIndex: u32,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadPossibleFriendlyName(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    PossibleSettingIndex: u32,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadPossibleValue(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    Type: ?*u32,
    PossibleSettingIndex: u32,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadSettingAttributes(
    SubGroupGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadValueIncrement(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    ValueIncrement: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadValueMax(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    ValueMaximum: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadValueMin(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    ValueMinimum: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReadValueUnitsSpecifier(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: ?*u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "powrprof" fn PowerRegisterForEffectivePowerModeNotifications(
    Version: u32,
    Callback: ?EFFECTIVE_POWER_MODE_CALLBACK,
    Context: ?*anyopaque,
    RegistrationHandle: ?*?*anyopaque,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows8.0'
pub extern "powrprof" fn PowerRegisterSuspendResumeNotification(
    Flags: u32,
    Recipient: ?HANDLE,
    RegistrationHandle: ?*?*anyopaque,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerRemovePowerSetting(
    PowerSettingSubKeyGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerReplaceDefaultPowerSchemes(
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows8.1'
pub extern "powrprof" fn PowerReportThermalEvent(
    Event: ?*THERMAL_EVENT,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerRestoreDefaultPowerSchemes(
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerRestoreIndividualDefaultPowerScheme(
    SchemeGuid: ?*const Guid,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerSetActiveScheme(
    UserRootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerSettingAccessCheck(
    AccessFlags: POWER_DATA_ACCESSOR,
    PowerGuid: ?*const Guid,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.1'
pub extern "powrprof" fn PowerSettingAccessCheckEx(
    AccessFlags: POWER_DATA_ACCESSOR,
    PowerGuid: ?*const Guid,
    AccessType: REG_SAM_FLAGS,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.1'
pub extern "powrprof" fn PowerSettingRegisterNotification(
    SettingGuid: ?*const Guid,
    Flags: POWER_SETTING_REGISTER_NOTIFICATION_FLAGS,
    Recipient: ?HANDLE,
    RegistrationHandle: ?*?*anyopaque,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.1'
pub extern "powrprof" fn PowerSettingUnregisterNotification(
    RegistrationHandle: ?HPOWERNOTIFY,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "powrprof" fn PowerUnregisterFromEffectivePowerModeNotifications(
    RegistrationHandle: ?*anyopaque,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows8.0'
pub extern "powrprof" fn PowerUnregisterSuspendResumeNotification(
    RegistrationHandle: ?HPOWERNOTIFY,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteACDefaultIndex(
    RootSystemPowerKey: ?HKEY,
    SchemePersonalityGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    DefaultAcIndex: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteACValueIndex(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    AcValueIndex: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteDCDefaultIndex(
    RootSystemPowerKey: ?HKEY,
    SchemePersonalityGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    DefaultDcIndex: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteDCValueIndex(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    DcValueIndex: u32,
) callconv(.winapi) u32;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteDescription(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteFriendlyName(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteIconResourceSpecifier(
    RootPowerKey: ?HKEY,
    SchemeGuid: ?*const Guid,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWritePossibleDescription(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    PossibleSettingIndex: u32,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWritePossibleFriendlyName(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    PossibleSettingIndex: u32,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWritePossibleValue(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    Type: u32,
    PossibleSettingIndex: u32,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteSettingAttributes(
    SubGroupGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    Attributes: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteValueIncrement(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    ValueIncrement: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteValueMax(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    ValueMaximum: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteValueMin(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    ValueMinimum: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "powrprof" fn PowerWriteValueUnitsSpecifier(
    RootPowerKey: ?HKEY,
    SubGroupOfPowerSettingsGuid: ?*const Guid,
    PowerSettingGuid: ?*const Guid,
    /// parameter "BufferSize" is the size in bytes
    Buffer: ?*u8,
    BufferSize: u32,
) callconv(.winapi) WIN32_ERROR;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn ReadGlobalPwrPolicy(
    pGlobalPowerPolicy: ?*GLOBAL_POWER_POLICY,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn ReadProcessorPwrScheme(
    uiID: u32,
    pMachineProcessorPowerPolicy: ?*MACHINE_PROCESSOR_POWER_POLICY,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn ReadPwrScheme(
    uiID: u32,
    pPowerPolicy: ?*POWER_POLICY,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn SetActivePwrScheme(
    uiID: u32,
    pGlobalPowerPolicy: ?*GLOBAL_POWER_POLICY,
    pPowerPolicy: ?*POWER_POLICY,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn SetSuspendState(
    bHibernate: BOOLEAN,
    bForce: BOOLEAN,
    bWakeupEventsDisabled: BOOLEAN,
) callconv(.winapi) BOOLEAN;

pub extern "powrprof" fn ValidatePowerPolicies(
    pGlobalPowerPolicy: ?*GLOBAL_POWER_POLICY,
    pPowerPolicy: ?*POWER_POLICY,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn WriteGlobalPwrPolicy(
    pGlobalPowerPolicy: ?*GLOBAL_POWER_POLICY,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn WriteProcessorPwrScheme(
    uiID: u32,
    pMachineProcessorPowerPolicy: ?*MACHINE_PROCESSOR_POWER_POLICY,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows5.1.2600'
pub extern "powrprof" fn WritePwrScheme(
    puiID: ?*u32,
    lpszSchemeName: ?[*:0]const u16,
    lpszDescription: ?[*:0]const u16,
    lpScheme: ?*POWER_POLICY,
) callconv(.winapi) BOOLEAN;


//--------------------------------------------------------------------------------
// Section: Imports (24)
//--------------------------------------------------------------------------------
const Guid = @import("../win32/zig.zig").Guid;
const ADMINISTRATOR_POWER_POLICY = @import("../win32/system/power.zig").ADMINISTRATOR_POWER_POLICY;
const BOOL = i32;
const BOOLEAN = u8;
const EFFECTIVE_POWER_MODE_CALLBACK = @import("../win32/system/power.zig").EFFECTIVE_POWER_MODE_CALLBACK;
const GLOBAL_POWER_POLICY = @import("../win32/system/power.zig").GLOBAL_POWER_POLICY;
const HANDLE = @import("../win32/foundation.zig").HANDLE;
const HKEY = @import("../win32/system/registry.zig").HKEY;
const HPOWERNOTIFY = @import("../win32/system/power.zig").HPOWERNOTIFY;
const HRESULT = @import("../win32/zig.zig").HRESULT;
const LPARAM = isize;
const MACHINE_PROCESSOR_POWER_POLICY = @import("../win32/system/power.zig").MACHINE_PROCESSOR_POWER_POLICY;
const NTSTATUS = @import("std").os.windows.NTSTATUS;
const POWER_DATA_ACCESSOR = @import("../win32/system/power.zig").POWER_DATA_ACCESSOR;
const POWER_INFORMATION_LEVEL = @import("../win32/system/power.zig").POWER_INFORMATION_LEVEL;
const POWER_PLATFORM_ROLE = @import("../win32/system/power.zig").POWER_PLATFORM_ROLE;
const POWER_PLATFORM_ROLE_VERSION = @import("../win32/system/power.zig").POWER_PLATFORM_ROLE_VERSION;
const POWER_POLICY = @import("../win32/system/power.zig").POWER_POLICY;
const POWER_SETTING_REGISTER_NOTIFICATION_FLAGS = @import("../win32/system/power.zig").POWER_SETTING_REGISTER_NOTIFICATION_FLAGS;
const PWRSCHEMESENUMPROC = @import("../win32/system/power.zig").PWRSCHEMESENUMPROC;
const REG_SAM_FLAGS = @import("../win32/system/registry.zig").REG_SAM_FLAGS;
const SYSTEM_POWER_CAPABILITIES = @import("../win32/system/power.zig").SYSTEM_POWER_CAPABILITIES;
const THERMAL_EVENT = @import("../win32/system/power.zig").THERMAL_EVENT;
const WIN32_ERROR = @import("../win32/foundation.zig").WIN32_ERROR;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
