//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (19)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjAllocateAlignedBuffer(
    namespaceVirtualizationContext: PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT,
    size: usize,
) callconv(.winapi) ?*anyopaque;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjClearNegativePathCache(
    namespaceVirtualizationContext: PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT,
    totalEntryNumber: ?*u32,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjCompleteCommand(
    namespaceVirtualizationContext: PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT,
    commandId: i32,
    completionResult: HRESULT,
    extendedParameters: ?*PRJ_COMPLETE_COMMAND_EXTENDED_PARAMETERS,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.17763'
// This function from dll 'PROJECTEDFSLIB.dll' is being skipped because it has some sort of issue
pub fn PrjDeleteFile() void { @panic("this function is not working"); }

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjDoesNameContainWildCards(
    fileName: ?[*:0]const u16,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjFileNameCompare(
    fileName1: ?[*:0]const u16,
    fileName2: ?[*:0]const u16,
) callconv(.winapi) i32;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjFileNameMatch(
    fileNameToCheck: ?[*:0]const u16,
    pattern: ?[*:0]const u16,
) callconv(.winapi) BOOLEAN;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjFillDirEntryBuffer(
    fileName: ?[*:0]const u16,
    fileBasicInfo: ?*PRJ_FILE_BASIC_INFO,
    dirEntryBufferHandle: PRJ_DIR_ENTRY_BUFFER_HANDLE,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.19041'
pub extern "projectedfslib" fn PrjFillDirEntryBuffer2(
    dirEntryBufferHandle: PRJ_DIR_ENTRY_BUFFER_HANDLE,
    fileName: ?[*:0]const u16,
    fileBasicInfo: ?*PRJ_FILE_BASIC_INFO,
    extendedInfo: ?*PRJ_EXTENDED_INFO,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjFreeAlignedBuffer(
    buffer: ?*anyopaque,
) callconv(.winapi) void;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjGetOnDiskFileState(
    destinationFileName: ?[*:0]const u16,
    fileState: ?*PRJ_FILE_STATE,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjGetVirtualizationInstanceInfo(
    namespaceVirtualizationContext: PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT,
    virtualizationInstanceInfo: ?*PRJ_VIRTUALIZATION_INSTANCE_INFO,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjMarkDirectoryAsPlaceholder(
    rootPathName: ?[*:0]const u16,
    targetPathName: ?[*:0]const u16,
    versionInfo: ?*const PRJ_PLACEHOLDER_VERSION_INFO,
    virtualizationInstanceID: ?*const Guid,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjStartVirtualizing(
    virtualizationRootPath: ?[*:0]const u16,
    callbacks: ?*const PRJ_CALLBACKS,
    instanceContext: ?*const anyopaque,
    options: ?*const PRJ_STARTVIRTUALIZING_OPTIONS,
    namespaceVirtualizationContext: ?*PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjStopVirtualizing(
    namespaceVirtualizationContext: PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT,
) callconv(.winapi) void;

// TODO: this type is limited to platform 'windows10.0.17763'
// This function from dll 'PROJECTEDFSLIB.dll' is being skipped because it has some sort of issue
pub fn PrjUpdateFileIfNeeded() void { @panic("this function is not working"); }

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjWriteFileData(
    namespaceVirtualizationContext: PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT,
    dataStreamId: ?*const Guid,
    /// parameter "length" is the size in bytes
    buffer: ?*anyopaque,
    byteOffset: u64,
    length: u32,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.17763'
pub extern "projectedfslib" fn PrjWritePlaceholderInfo(
    namespaceVirtualizationContext: PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT,
    destinationFileName: ?[*:0]const u16,
    /// parameter "placeholderInfoSize" is the size in bytes
    placeholderInfo: ?*const PRJ_PLACEHOLDER_INFO,
    placeholderInfoSize: u32,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.19041'
pub extern "projectedfslib" fn PrjWritePlaceholderInfo2(
    namespaceVirtualizationContext: PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT,
    destinationFileName: ?[*:0]const u16,
    /// parameter "placeholderInfoSize" is the size in bytes
    placeholderInfo: ?*const PRJ_PLACEHOLDER_INFO,
    placeholderInfoSize: u32,
    ExtendedInfo: ?*const PRJ_EXTENDED_INFO,
) callconv(.winapi) HRESULT;


//--------------------------------------------------------------------------------
// Section: Imports (14)
//--------------------------------------------------------------------------------
const Guid = @import("../win32/zig.zig").Guid;
const BOOLEAN = u8;
const HRESULT = @import("../win32/zig.zig").HRESULT;
const PRJ_CALLBACKS = @import("../win32/storage/projected_file_system.zig").PRJ_CALLBACKS;
const PRJ_COMPLETE_COMMAND_EXTENDED_PARAMETERS = @import("../win32/storage/projected_file_system.zig").PRJ_COMPLETE_COMMAND_EXTENDED_PARAMETERS;
const PRJ_DIR_ENTRY_BUFFER_HANDLE = @import("../win32/storage/projected_file_system.zig").PRJ_DIR_ENTRY_BUFFER_HANDLE;
const PRJ_EXTENDED_INFO = @import("../win32/storage/projected_file_system.zig").PRJ_EXTENDED_INFO;
const PRJ_FILE_BASIC_INFO = @import("../win32/storage/projected_file_system.zig").PRJ_FILE_BASIC_INFO;
const PRJ_FILE_STATE = @import("../win32/storage/projected_file_system.zig").PRJ_FILE_STATE;
const PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT = @import("../win32/storage/projected_file_system.zig").PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT;
const PRJ_PLACEHOLDER_INFO = @import("../win32/storage/projected_file_system.zig").PRJ_PLACEHOLDER_INFO;
const PRJ_PLACEHOLDER_VERSION_INFO = @import("../win32/storage/projected_file_system.zig").PRJ_PLACEHOLDER_VERSION_INFO;
const PRJ_STARTVIRTUALIZING_OPTIONS = @import("../win32/storage/projected_file_system.zig").PRJ_STARTVIRTUALIZING_OPTIONS;
const PRJ_VIRTUALIZATION_INSTANCE_INFO = @import("../win32/storage/projected_file_system.zig").PRJ_VIRTUALIZATION_INSTANCE_INFO;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
