//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (21)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "wer" fn WerAddExcludedApplication(
    pwzExeName: ?[*:0]const u16,
    bAllUsers: BOOL,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.15063'
pub extern "wer" fn WerFreeString(
    pwszStr: ?[*:0]const u16,
) callconv(.winapi) void;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "wer" fn WerRemoveExcludedApplication(
    pwzExeName: ?[*:0]const u16,
    bAllUsers: BOOL,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "wer" fn WerReportAddDump(
    hReportHandle: HREPORT,
    hProcess: ?HANDLE,
    hThread: ?HANDLE,
    dumpType: WER_DUMP_TYPE,
    pExceptionParam: ?*WER_EXCEPTION_INFORMATION,
    pDumpCustomOptions: ?*WER_DUMP_CUSTOM_OPTIONS,
    dwFlags: u32,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "wer" fn WerReportAddFile(
    hReportHandle: HREPORT,
    pwzPath: ?[*:0]const u16,
    repFileType: WER_FILE_TYPE,
    dwFileFlags: WER_FILE,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "wer" fn WerReportCloseHandle(
    hReportHandle: HREPORT,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "wer" fn WerReportCreate(
    pwzEventType: ?[*:0]const u16,
    repType: WER_REPORT_TYPE,
    pReportInformation: ?*WER_REPORT_INFORMATION,
    phReportHandle: ?*HREPORT,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "wer" fn WerReportSetParameter(
    hReportHandle: HREPORT,
    dwparamID: u32,
    pwzName: ?[*:0]const u16,
    pwzValue: ?[*:0]const u16,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "wer" fn WerReportSetUIOption(
    hReportHandle: HREPORT,
    repUITypeID: WER_REPORT_UI,
    pwzValue: ?[*:0]const u16,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows6.0.6000'
pub extern "wer" fn WerReportSubmit(
    hReportHandle: HREPORT,
    consent: WER_CONSENT,
    dwFlags: WER_SUBMIT_FLAGS,
    pSubmitResult: ?*WER_SUBMIT_RESULT,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.15063'
pub extern "wer" fn WerStoreClose(
    hReportStore: HREPORTSTORE,
) callconv(.winapi) void;

// TODO: this type is limited to platform 'windows10.0.15063'
pub extern "wer" fn WerStoreGetFirstReportKey(
    hReportStore: HREPORTSTORE,
    ppszReportKey: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.15063'
pub extern "wer" fn WerStoreGetNextReportKey(
    hReportStore: HREPORTSTORE,
    ppszReportKey: ?*?[*:0]u16,
) callconv(.winapi) HRESULT;

pub extern "wer" fn WerStoreGetReportCount(
    hReportStore: HREPORTSTORE,
    pdwReportCount: ?*u32,
) callconv(.winapi) HRESULT;

pub extern "wer" fn WerStoreGetSizeOnDisk(
    hReportStore: HREPORTSTORE,
    pqwSizeInBytes: ?*u64,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.15063'
pub extern "wer" fn WerStoreOpen(
    repStoreType: REPORT_STORE_TYPES,
    phReportStore: ?*HREPORTSTORE,
) callconv(.winapi) HRESULT;

pub extern "wer" fn WerStorePurge(
) callconv(.winapi) HRESULT;

pub extern "wer" fn WerStoreQueryReportMetadataV1(
    hReportStore: HREPORTSTORE,
    pszReportKey: ?[*:0]const u16,
    pReportMetadata: ?*WER_REPORT_METADATA_V1,
) callconv(.winapi) HRESULT;

// TODO: this type is limited to platform 'windows10.0.15063'
pub extern "wer" fn WerStoreQueryReportMetadataV2(
    hReportStore: HREPORTSTORE,
    pszReportKey: ?[*:0]const u16,
    pReportMetadata: ?*WER_REPORT_METADATA_V2,
) callconv(.winapi) HRESULT;

pub extern "wer" fn WerStoreQueryReportMetadataV3(
    hReportStore: HREPORTSTORE,
    pszReportKey: ?[*:0]const u16,
    pReportMetadata: ?*WER_REPORT_METADATA_V3,
) callconv(.winapi) HRESULT;

pub extern "wer" fn WerStoreUploadReport(
    hReportStore: HREPORTSTORE,
    pszReportKey: ?[*:0]const u16,
    dwFlags: u32,
    pSubmitResult: ?*WER_SUBMIT_RESULT,
) callconv(.winapi) HRESULT;


//--------------------------------------------------------------------------------
// Section: Imports (20)
//--------------------------------------------------------------------------------
const BOOL = i32;
const HANDLE = @import("../win32/foundation.zig").HANDLE;
const HREPORT = @import("../win32/system/error_reporting.zig").HREPORT;
const HREPORTSTORE = @import("../win32/system/error_reporting.zig").HREPORTSTORE;
const HRESULT = @import("../win32/zig.zig").HRESULT;
const REPORT_STORE_TYPES = @import("../win32/system/error_reporting.zig").REPORT_STORE_TYPES;
const WER_CONSENT = @import("../win32/system/error_reporting.zig").WER_CONSENT;
const WER_DUMP_CUSTOM_OPTIONS = @import("../win32/system/error_reporting.zig").WER_DUMP_CUSTOM_OPTIONS;
const WER_DUMP_TYPE = @import("../win32/system/error_reporting.zig").WER_DUMP_TYPE;
const WER_EXCEPTION_INFORMATION = @import("../win32/system/error_reporting.zig").WER_EXCEPTION_INFORMATION;
const WER_FILE = @import("../win32/system/error_reporting.zig").WER_FILE;
const WER_FILE_TYPE = @import("../win32/system/error_reporting.zig").WER_FILE_TYPE;
const WER_REPORT_INFORMATION = @import("../win32/system/error_reporting.zig").WER_REPORT_INFORMATION;
const WER_REPORT_METADATA_V1 = @import("../win32/system/error_reporting.zig").WER_REPORT_METADATA_V1;
const WER_REPORT_METADATA_V2 = @import("../win32/system/error_reporting.zig").WER_REPORT_METADATA_V2;
const WER_REPORT_METADATA_V3 = @import("../win32/system/error_reporting.zig").WER_REPORT_METADATA_V3;
const WER_REPORT_TYPE = @import("../win32/system/error_reporting.zig").WER_REPORT_TYPE;
const WER_REPORT_UI = @import("../win32/system/error_reporting.zig").WER_REPORT_UI;
const WER_SUBMIT_FLAGS = @import("../win32/system/error_reporting.zig").WER_SUBMIT_FLAGS;
const WER_SUBMIT_RESULT = @import("../win32/system/error_reporting.zig").WER_SUBMIT_RESULT;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
