//! NOTE: this file is autogenerated, DO NOT MODIFY
//--------------------------------------------------------------------------------
// Section: Functions (1)
//--------------------------------------------------------------------------------
pub extern "windows.ai.machinelearning" fn MLCreateOperatorRegistry(
    registry: **IMLOperatorRegistry,
) callconv(.winapi) HRESULT;


//--------------------------------------------------------------------------------
// Section: Imports (2)
//--------------------------------------------------------------------------------
const HRESULT = @import("../win32/zig.zig").HRESULT;
const IMLOperatorRegistry = @import("../win32/ai/machine_learning/win_ml.zig").IMLOperatorRegistry;

test {
    @setEvalBranchQuota(
        comptime @import("std").meta.declarations(@This()).len * 3
    );

    // reference all the pub declarations
    if (!@import("builtin").is_test) return;
    inline for (comptime @import("std").meta.declarations(@This())) |decl| {
        _ = @field(@This(), decl.name);
    }
}
